{
  "openapi": "3.0.0",
  "info": {
    "title": "viagogo API v2",
    "description": "viagogo's v2 REST API",
    "version": "2.249.0.0",
    "x-logo": {
      "url": "https://img.vggcdn.net/img/assets/logo/viagogo_logo_apidocs.png",
      "backgroundColor": "#222222"
    }
  },
  "servers": [
    {
      "url": "https://api.viagogo.net/v2",
      "description": "Production"
    },
    {
      "url": "https://sandbox.api.viagogo.net/v2",
      "description": "Sandbox"
    }
  ],
  "paths": {
    "/currencies/{currencyCode}": {
      "get": {
        "tags": [
          "Currencies"
        ],
        "summary": "Get a currency",
        "operationId": "Currencies_GetCurrency"
      }
    },
    "/currencies": {
      "get": {
        "tags": [
          "Currencies"
        ],
        "summary": "List currencies",
        "operationId": "Currencies_GetCurrencies"
      }
    },
    "/categories/{categoryId}": {
      "get": {
        "tags": [
          "Categories"
        ],
        "summary": "Get a category",
        "operationId": "Categories_GetCategory"
      }
    },
    "/categories/{categoryId}/children": {
      "get": {
        "tags": [
          "Categories"
        ],
        "summary": "List category children",
        "description": "List categories that are direct-descendants of a category.",
        "operationId": "Categories_GetChildren"
      }
    },
    "/events/{eventId}": {
      "get": {
        "tags": [
          "Events"
        ],
        "summary": "Get an event",
        "operationId": "Events_Get"
      }
    },
    "/categories/{categoryId}/events": {
      "get": {
        "tags": [
          "Events"
        ],
        "summary": "List events for a category",
        "operationId": "Events_GetCategoryEvents"
      }
    },
    "/venues/{venueId}": {
      "get": {
        "tags": [
          "Venues"
        ],
        "summary": "Get a venue",
        "operationId": "Venues_GetVenue"
      }
    },
    "/venues": {
      "get": {
        "tags": [
          "Venues"
        ],
        "summary": "List venues",
        "operationId": "Venues_GetVenues"
      }
    },
    "/metroareas/{metroAreaId}": {
      "get": {
        "tags": [
          "MetroAreas"
        ],
        "summary": "Get a metro area",
        "operationId": "MetroAreas_GetMetroArea"
      }
    },
    "/metroareas": {
      "get": {
        "tags": [
          "MetroAreas"
        ],
        "summary": "List metro areas",
        "operationId": "MetroAreas_GetMetroAreas"
      }
    },
    "/events/{eventId}/listings": {
      "get": {
        "tags": [
          "Listings"
        ],
        "summary": "List listings for an event",
        "operationId": "Listings_GetEventListings"
      }
    },
    "/listings/{listingId}": {
      "get": {
        "tags": [
          "Listings"
        ],
        "summary": "Get a listing",
        "operationId": "Listings_GetListing"
      }
    },
    "/search": {
      "get": {
        "tags": [
          "Search"
        ],
        "summary": "Search for entities",
        "description": "Search for entities that match a given query",
        "operationId": "Search_Get"
      }
    },
    "": {
      "get": {
        "tags": [
          "Root"
        ],
        "summary": "Get the root API resource",
        "operationId": "ApiRoot_Get"
      }
    },
    "/sellerlistings/{listingId}": {
      "patch": {
        "tags": [
          "SellerListings"
        ],
        "summary": "Update a seller listing",
        "operationId": "SellerListings_Patch",
        "security": [
          {
            "OAuth2": [
              "write:sellerlistings"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "SellerListings"
        ],
        "summary": "Get a seller listing",
        "operationId": "SellerListings_Get",
        "security": [
          {
            "OAuth2": [
              "read:sellerlistings"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "SellerListings"
        ],
        "summary": "Delete a seller listing",
        "operationId": "SellerListings_DeleteListing",
        "security": [
          {
            "OAuth2": [
              "write:sellerlistings"
            ]
          }
        ]
      }
    },
    "/sellerlistings": {
      "get": {
        "tags": [
          "SellerListings"
        ],
        "summary": "List seller listings",
        "description": "List seller listings for the authenticated user.",
        "operationId": "SellerListings_GetSellerListings",
        "security": [
          {
            "OAuth2": [
              "read:sellerlistings"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "SellerListings"
        ],
        "summary": "Create a seller listing for a requested event",
        "description": "Creates a seller listing for an event requested by the current user.",
        "operationId": "SellerListings_CreateListingForRequestedEvent",
        "security": [
          {
            "OAuth2": [
              "write:sellerlistings",
              "write:requestedevents"
            ]
          }
        ]
      }
    },
    "/events/{eventId}/sellerlistingpreview": {
      "post": {
        "tags": [
          "SellerListings"
        ],
        "summary": "Preview a seller listing",
        "description": "Creates a preview of a seller listing. The listing will not have an `id` and will not actually be created on the viagogo marketplace.",
        "operationId": "SellerListings_CreateListingPreview",
        "security": [
          {
            "OAuth2": [
              "write:sellerlistings"
            ]
          }
        ]
      }
    },
    "/sellerlistings/{listingId}/updatepreview": {
      "post": {
        "tags": [
          "SellerListings"
        ],
        "summary": "Preview a seller listing update",
        "description": "Creates a preview of an update to a seller listing. The updates will not actually be applied to the listing on the viagogo marketplace.",
        "operationId": "SellerListings_UpdateListingPreview",
        "security": [
          {
            "OAuth2": [
              "write:sellerlistings"
            ]
          }
        ]
      }
    },
    "/sellerlistingpreview": {
      "post": {
        "tags": [
          "SellerListings"
        ],
        "summary": "Preview a seller listing for a requested event",
        "description": "Creates a preview of a seller listing for an event requested by the current user. The listing will not have an `id` and will not actually be created on the viagogo marketplace.",
        "operationId": "SellerListings_CreateListingPreviewForRequestedEvent",
        "security": [
          {
            "OAuth2": [
              "write:sellerlistings",
              "write:requestedevents"
            ]
          }
        ]
      }
    },
    "/events/{eventId}/sellerlistings": {
      "post": {
        "tags": [
          "SellerListings"
        ],
        "summary": "Create a seller listing",
        "operationId": "SellerListings_CreateListing",
        "security": [
          {
            "OAuth2": [
              "write:sellerlistings"
            ]
          }
        ]
      }
    },
    "/externalsellerlistings/{externallistingId}": {
      "get": {
        "tags": [
          "SellerListings"
        ],
        "summary": "Get a seller listing by external ID",
        "description": "Get a seller listing by identifier that has been assigned to the listing in an external inventory management system.",
        "operationId": "SellerListings_GetByExternalListingId",
        "security": [
          {
            "OAuth2": [
              "read:sellerlistings"
            ]
          }
        ]
      }
    },
    "/externalsellerlistings/{externalId}": {
      "patch": {
        "tags": [
          "SellerListings"
        ],
        "summary": "Update a seller listing by external ID",
        "description": "Update a seller listing by identifier that has been assigned to the listing in an external inventory management system.",
        "operationId": "SellerListings_PatchByExternalListingId",
        "security": [
          {
            "OAuth2": [
              "write:sellerlistings"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "SellerListings"
        ],
        "summary": "Delete a seller listing by external ID",
        "description": "Delete a seller listing by identifier that has been assigned to the listing in an external inventory management system.",
        "operationId": "SellerListings_DeleteListingByExternalListingId",
        "security": [
          {
            "OAuth2": [
              "write:sellerlistings"
            ]
          }
        ]
      }
    },
    "/events/{eventId}/listingconstraints": {
      "get": {
        "tags": [
          "ListingConstraints"
        ],
        "summary": "List listing constraints for an event",
        "operationId": "ListingConstraints_GetEventListingConstraints"
      }
    },
    "/sellerlistings/{listingId}/constraints": {
      "get": {
        "tags": [
          "ListingConstraints"
        ],
        "summary": "Get listing constraints for a seller listing",
        "operationId": "ListingConstraints_GetListingConstraints",
        "security": [
          {
            "OAuth2": [
              "write:sellerlistings"
            ]
          }
        ]
      }
    },
    "/listingconstraints": {
      "put": {
        "tags": [
          "ListingConstraints"
        ],
        "summary": "Get listing constraints for a requested event",
        "description": "Get listings constraints for an event requested by the current user.",
        "operationId": "ListingConstraints_PutRequestedEventListingConstraints",
        "security": [
          {
            "OAuth2": [
              "write:sellerlistings",
              "write:requestedevents"
            ]
          }
        ]
      }
    },
    "/sellerevents": {
      "get": {
        "tags": [
          "SellerEvents"
        ],
        "summary": "List seller events",
        "description": "List events with listings that belong to the authenticated user.",
        "operationId": "SellerEvents_GetSellerEvents",
        "security": [
          {
            "OAuth2": [
              "internal",
              "read:sellerlistings"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "SellerEvents"
        ],
        "summary": "Create a requested event",
        "description": "Request for an event to be created on the viagogo marketplace.",
        "operationId": "SellerEvents_PutSellerRequestedEvent",
        "security": [
          {
            "OAuth2": [
              "write:requestedevents"
            ]
          }
        ]
      }
    },
    "/sellerevents/{eventIdOrRequestedEventId}": {
      "get": {
        "tags": [
          "SellerEvents"
        ],
        "summary": "Get a seller event",
        "description": "Get an event with listings belonging to the current user",
        "operationId": "SellerEvents_GetSellerEvent",
        "security": [
          {
            "OAuth2": [
              "read:sellerlistings"
            ]
          }
        ]
      }
    },
    "/sales/{saleId}/shipments/{shipmentId}/label": {
      "get": {
        "tags": [
          "Shipments (Sales)"
        ],
        "summary": "Get shipping label for a sale",
        "operationId": "Shipments_GetSaleShippingLabel",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:sales"
            ]
          }
        ]
      }
    },
    "/sales/{saleId}/shipments": {
      "get": {
        "tags": [
          "Shipments (Sales)"
        ],
        "summary": "List shipments for a sale",
        "operationId": "Shipments_GetSaleShipments",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:sales"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Shipments (Sales)"
        ],
        "summary": "Print a shipping label for a sale",
        "operationId": "Shipments_PutOrGetSaleShipmentLabel",
        "security": [
          {
            "OAuth2": [
              "write:user",
              "write:sales"
            ]
          }
        ]
      }
    },
    "/sales/{saleId}/shipments/{shipmentId}": {
      "patch": {
        "tags": [
          "Shipments (Sales)"
        ],
        "summary": "Update a shipment for a sale",
        "operationId": "Shipments_PatchSaleShipment",
        "security": [
          {
            "OAuth2": [
              "write:user",
              "write:sales"
            ]
          }
        ]
      }
    },
    "/sellerlistings/{listingId}/shipments/{shipmentId}/label": {
      "get": {
        "tags": [
          "Shipments (Inventory)"
        ],
        "summary": "Get a shipping label for a seller listing",
        "operationId": "Shipments_GetListingShippingLabel",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:sellerlistings"
            ]
          }
        ]
      }
    },
    "/sellerlistings/{listingId}/shipments": {
      "get": {
        "tags": [
          "Shipments (Inventory)"
        ],
        "summary": "List shipments for a seller listing",
        "operationId": "Shipments_GetListingShipments",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:sellerlistings"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Shipments (Inventory)"
        ],
        "summary": "Print a shipping label for a seller listing",
        "operationId": "Shipments_PutOrGetListingShipmentLabel",
        "security": [
          {
            "OAuth2": [
              "write:user",
              "write:sellerlistings"
            ]
          }
        ]
      }
    },
    "/sellerlistings/{listingId}/shipments/{shipmentId}": {
      "patch": {
        "tags": [
          "Shipments (Inventory)"
        ],
        "summary": "Update a shipment for a seller listing",
        "operationId": "Shipments_PatchListingShipment",
        "security": [
          {
            "OAuth2": [
              "write:user",
              "write:sellerlistings"
            ]
          }
        ]
      }
    },
    "/sales/{saleId}/eticketuploads": {
      "post": {
        "tags": [
          "E-Tickets (Sales)"
        ],
        "summary": "Upload e-tickets for a sale",
        "operationId": "ETicket_UploadSaleETicket",
        "security": [
          {
            "OAuth2": [
              "write:user",
              "write:sales"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "E-Tickets (Sales)"
        ],
        "summary": "List e-ticket uploads for a sale",
        "operationId": "ETicket_GetSaleETicketUploads",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:sales"
            ]
          }
        ]
      }
    },
    "/sales/{saleId}/etickets": {
      "get": {
        "tags": [
          "E-Tickets (Sales)"
        ],
        "summary": "List e-tickets for a sale",
        "operationId": "ETicket_GetSaleETickets",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:sales"
            ]
          }
        ]
      }
    },
    "/sellerlistings/{listingId}/eticketuploads": {
      "post": {
        "tags": [
          "E-Tickets (Inventory)"
        ],
        "summary": "Upload e-tickets for a seller listing",
        "operationId": "ETicket_UploadListingETicket",
        "security": [
          {
            "OAuth2": [
              "write:sellerlistings"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "E-Tickets (Inventory)"
        ],
        "summary": "List e-ticket uploads for a seller listing",
        "operationId": "ETicket_GetListingETicketUploads",
        "security": [
          {
            "OAuth2": [
              "read:sellerlistings"
            ]
          }
        ]
      }
    },
    "/events/{eventId}/eticketuploads": {
      "post": {
        "tags": [
          "E-Tickets (Inventory)"
        ],
        "summary": "Upload e-tickets for an event",
        "operationId": "ETicket_UploadEventETicket",
        "security": [
          {
            "OAuth2": [
              "write:user"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "E-Tickets (Inventory)"
        ],
        "summary": "List e-ticket uploads for an event",
        "operationId": "ETicket_GetEventETicketUploads",
        "security": [
          {
            "OAuth2": [
              "read:user"
            ]
          }
        ]
      }
    },
    "/sellerlistings/{listingId}/etickets": {
      "get": {
        "tags": [
          "E-Tickets (Inventory)"
        ],
        "summary": "List e-tickets for a seller listing",
        "operationId": "ETicket_GetListingETickets",
        "security": [
          {
            "OAuth2": [
              "read:sellerlistings"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "E-Tickets (Inventory)"
        ],
        "summary": "Mark-back e-tickets from a seller listing",
        "description": "Removes a certain number of e-tickets that you no longer wish to sell from your listing.",
        "operationId": "ETicket_MarkBackETickets",
        "security": [
          {
            "OAuth2": [
              "write:sellerlistings"
            ]
          }
        ]
      }
    },
    "/sales/{saleId}/etickets/{eticketId}": {
      "delete": {
        "tags": [
          "E-Tickets (Sales)"
        ],
        "summary": "Delete e-ticket from a sale",
        "operationId": "ETicket_DeleteSaleETicket",
        "security": [
          {
            "OAuth2": [
              "write:user",
              "write:sales"
            ]
          }
        ]
      }
    },
    "/sellerlistings/{listingId}/etickets/{ETicketId}": {
      "delete": {
        "tags": [
          "E-Tickets (Inventory)"
        ],
        "summary": "Delete e-ticket from a seller listing",
        "operationId": "ETicket_DeleteListingETicket",
        "security": [
          {
            "OAuth2": [
              "write:sellerlistings"
            ]
          }
        ]
      }
    },
    "/events/{eventId}/etickets/{eticketId}": {
      "delete": {
        "tags": [
          "E-Tickets (Inventory)"
        ],
        "summary": "Delete e-ticket from an event",
        "operationId": "ETicket_DeleteEventETicket",
        "security": [
          {
            "OAuth2": [
              "write:user"
            ]
          }
        ]
      }
    },
    "/sales": {
      "get": {
        "tags": [
          "Sales"
        ],
        "summary": "List sales",
        "description": "List sales for the authenticated user.",
        "operationId": "Sales_GetSales",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:sales"
            ]
          }
        ]
      }
    },
    "/sales/{saleId}": {
      "get": {
        "tags": [
          "Sales"
        ],
        "summary": "Get a sale",
        "operationId": "Sales_Get",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:sales"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Sales"
        ],
        "summary": "Update a sale",
        "operationId": "Sales_Patch",
        "security": [
          {
            "OAuth2": [
              "write:user",
              "write:sales"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Sales"
        ],
        "summary": "Reject a sale",
        "description": "Report a problem with a sale of tickets.",
        "operationId": "Sales_Delete",
        "security": [
          {
            "OAuth2": [
              "write:user",
              "write:sales"
            ]
          }
        ]
      }
    },
    "/payments": {
      "get": {
        "tags": [
          "Payments"
        ],
        "summary": "List payments",
        "description": "Lists payments for the authenticated user.",
        "operationId": "Payments_GetPayments",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:payment"
            ]
          }
        ]
      }
    },
    "/payments/{paymentId}": {
      "get": {
        "tags": [
          "Payments"
        ],
        "summary": "Get a payment",
        "operationId": "Payments_Get",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:payment"
            ]
          }
        ]
      }
    },
    "/payments/next": {
      "get": {
        "tags": [
          "Payments"
        ],
        "summary": "Preview next payment",
        "description": "Previews the next payment for the authenticated user. The payment will not have an `id` and is subject to changes.",
        "operationId": "Payments_GetNextPayment",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:payment"
            ]
          }
        ]
      }
    },
    "/salesaggregates": {
      "get": {
        "tags": [
          "SalesAggregates"
        ],
        "summary": "List sales aggregates",
        "description": "List aggregated sales data for the authenticated user.",
        "operationId": "SalesAggregates_GetSalesAggregates",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:sales"
            ]
          }
        ]
      }
    },
    "/etickets/{eticketId}/thumbnail": {
      "get": {
        "tags": [
          "E-Tickets (Sales)"
        ],
        "summary": "Get e-ticket thumbnail file",
        "description": "Download an image file containing a thumbnail of an E-Ticket",
        "operationId": "ETicketDocument_GetETicketThumbnail",
        "security": [
          {
            "OAuth2": [
              "read:user"
            ]
          }
        ]
      }
    },
    "/eticketuploads/{eticketUploadId}/document": {
      "get": {
        "tags": [
          "E-Tickets (Sales)"
        ],
        "summary": "Get e-ticket upload file",
        "description": "Download the original file that was uploaded.",
        "operationId": "ETicketDocument_GetETicketUploadDocument",
        "security": [
          {
            "OAuth2": [
              "read:user"
            ]
          }
        ]
      }
    },
    "/etickets/{eticketId}/document": {
      "get": {
        "tags": [
          "E-Tickets (Sales)"
        ],
        "summary": "Get e-ticket file",
        "description": "Download a PDF file containing an E-Ticket.",
        "operationId": "ETicketDocument_GetETicketDocument",
        "security": [
          {
            "OAuth2": [
              "read:user"
            ]
          }
        ]
      }
    },
    "/sellerlistings/{listingId}/markedbacketickets/{markedBackETicketId}/document": {
      "get": {
        "tags": [
          "E-Tickets (Inventory)"
        ],
        "summary": "Get marked back e-ticket file for seller listing",
        "operationId": "ETicketDocument_GetMarkedBackETicketDocument",
        "security": [
          {
            "OAuth2": [
              "read:sellerlistings"
            ]
          }
        ]
      }
    },
    "/webhooks": {
      "get": {
        "tags": [
          "Webhooks"
        ],
        "summary": "List webhooks",
        "description": "List webhooks for the authenticated user.",
        "operationId": "Webhooks_Get",
        "security": [
          {
            "OAuth2": [
              "read:webhooks"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Create a webhook",
        "operationId": "Webhooks_Post",
        "security": [
          {
            "OAuth2": [
              "write:webhooks"
            ]
          }
        ]
      }
    },
    "/webhooks/{webhookId}": {
      "get": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Get a webhook",
        "operationId": "Webhooks_Get2",
        "security": [
          {
            "OAuth2": [
              "read:webhooks"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Update a webhook",
        "operationId": "Webhooks_Patch",
        "security": [
          {
            "OAuth2": [
              "write:webhooks"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Delete a webhook",
        "operationId": "Webhooks_Delete",
        "security": [
          {
            "OAuth2": [
              "write:webhooks"
            ]
          }
        ]
      }
    },
    "/webhooks/{webhookId}/ping": {
      "post": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Ping a webhook",
        "description": "Triggers a request to be sent to your webhook. Call this endpoint to test your webhook.",
        "operationId": "Webhooks_PingWebhook",
        "security": [
          {
            "OAuth2": [
              "write:webhooks"
            ]
          }
        ]
      }
    },
    "/addresses": {
      "get": {
        "tags": [
          "Addresses"
        ],
        "summary": "List addresses",
        "description": "List addresses for the current user.",
        "operationId": "Addressess_GetUserAddresses",
        "security": [
          {
            "OAuth2": [
              "read:user"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Addresses"
        ],
        "summary": "Create an address",
        "operationId": "Addressess_Post",
        "security": [
          {
            "OAuth2": [
              "write:user"
            ]
          }
        ]
      }
    },
    "/addresses/{addressId}": {
      "get": {
        "tags": [
          "Addresses"
        ],
        "summary": "Get an address",
        "operationId": "Addressess_Get",
        "security": [
          {
            "OAuth2": [
              "read:user"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Addresses"
        ],
        "summary": "Update an address",
        "operationId": "Addressess_Patch",
        "security": [
          {
            "OAuth2": [
              "write:user"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Addresses"
        ],
        "summary": "Delete an address",
        "operationId": "Addressess_Delete",
        "security": [
          {
            "OAuth2": [
              "write:user"
            ]
          }
        ]
      }
    },
    "/paymentmethods": {
      "get": {
        "tags": [
          "PaymentMethods"
        ],
        "summary": "List payment methods",
        "description": "List payment methods for the authenticated user.",
        "operationId": "PaymentMethods_GetPaymentMethods",
        "security": [
          {
            "OAuth2": [
              "read:user"
            ]
          }
        ]
      }
    },
    "/paymentmethods/{paymentMethodId}": {
      "get": {
        "tags": [
          "PaymentMethods"
        ],
        "summary": "Get a payment method",
        "operationId": "PaymentMethods_GetPaymentMethod",
        "security": [
          {
            "OAuth2": [
              "read:user"
            ]
          }
        ]
      }
    },
    "/listings/{listingId}/paymentmethods": {
      "put": {
        "tags": [
          "PaymentMethods"
        ],
        "summary": "List payment methods for a listing",
        "operationId": "PaymentMethods_GetListingPaymentMethods",
        "security": [
          {
            "OAuth2": [
              "read:user"
            ]
          }
        ]
      }
    },
    "/user": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Get the authenticated user",
        "operationId": "User_Get",
        "security": [
          {
            "OAuth2": [
              "read:user"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "User"
        ],
        "summary": "Update the authenticated user",
        "operationId": "User_Patch",
        "security": [
          {
            "OAuth2": [
              "write:user"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "bearerFormat": "JWT",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://account.viagogo.com/authorize",
            "tokenUrl": "https://account.viagogo.com/oauth2/token",
            "refreshUrl": "https://account.viagogo.com/oauth2/token",
            "scopes": {
              "(no scope)": "Grants read-only access to public information like events, listings.",
              "read:user": "Grants read-only access to the user's account information, addresses, payment methods, purchases and sales.",
              "write:user": "Grants write access to the user’s account information, addresses, payment methods and sales.",
              "write:purchases": "Grants write access to the user’s purchases. This allows users to use your application to purchase listings.",
              "read:sellerlistings": "Grants read access to the user’s listings.",
              "write:sellerlistings": "Grants write access to the user’s listings. This allows users to use your application to create and update listings.",
              "read:webhooks": "Grants read access to the user’s webhooks.",
              "write:webhooks": "Grants write access to the user’s webhooks.",
              "write:requestedevents": "Grants write access to the user’s requested events. This allows users to use your application to request an event to be added to the viagogo platform.",
              "read:payment": "Grants read-only access to the user's payments",
              "read:sales": "Grants read-only access to the user's sales.",
              "write:sales": "Grants write access to the user's sales. This allows users to use your application to confirm and fulfill sales."
            }
          },
          "clientCredentials": {
            "tokenUrl": "https://account.viagogo.com/oauth2/token",
            "scopes": {}
          },
          "authorizationCode": {
            "authorizationUrl": "https://account.viagogo.com/authorize",
            "tokenUrl": "https://account.viagogo.com/oauth2/token",
            "refreshUrl": "https://account.viagogo.com/oauth2/token",
            "scopes": {
              "(no scope)": "Grants read-only access to public information like events, listings.",
              "read:user": "Grants read-only access to the user's account information, addresses, payment methods, purchases and sales.",
              "write:user": "Grants write access to the user’s account information, addresses, payment methods and sales.",
              "write:purchases": "Grants write access to the user’s purchases. This allows users to use your application to purchase listings.",
              "read:sellerlistings": "Grants read access to the user’s listings.",
              "write:sellerlistings": "Grants write access to the user’s listings. This allows users to use your application to create and update listings.",
              "read:webhooks": "Grants read access to the user’s webhooks.",
              "write:webhooks": "Grants write access to the user’s webhooks.",
              "write:requestedevents": "Grants write access to the user’s requested events. This allows users to use your application to request an event to be added to the viagogo platform.",
              "read:payment": "Grants read-only access to the user's payments",
              "read:sales": "Grants read-only access to the user's sales.",
              "write:sales": "Grants write access to the user's sales. This allows users to use your application to confirm and fulfill sales."
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Addresses"
    },
    {
      "name": "Categories"
    },
    {
      "name": "Currencies"
    },
    {
      "name": "E-Tickets (Inventory)"
    },
    {
      "name": "E-Tickets (Sales)"
    },
    {
      "name": "Events"
    },
    {
      "name": "ListingConstraints"
    },
    {
      "name": "Listings"
    },
    {
      "name": "MetroAreas"
    },
    {
      "name": "PaymentMethods"
    },
    {
      "name": "Payments"
    },
    {
      "name": "Root"
    },
    {
      "name": "Sales",
      "description": "View your sales details and fulfill your sales."
    },
    {
      "name": "SalesAggregates"
    },
    {
      "name": "Search"
    },
    {
      "name": "SellerEvents"
    },
    {
      "name": "SellerListings",
      "description": "List tickets, update your listings and search your inventory."
    },
    {
      "name": "Shipments (Inventory)"
    },
    {
      "name": "Shipments (Sales)"
    },
    {
      "name": "User"
    },
    {
      "name": "Venues"
    },
    {
      "name": "Webhooks"
    }
  ],
  "x-tagGroups": [
    {
      "name": "Discover",
      "tags": [
        "Categories",
        "Currencies",
        "Events",
        "Listings",
        "MetroAreas",
        "Root",
        "Search",
        "Venues"
      ]
    },
    {
      "name": "Manage Inventory",
      "tags": [
        "E-Tickets (Inventory)",
        "ListingConstraints",
        "SellerEvents",
        "SellerListings",
        "Shipments (Inventory)"
      ]
    },
    {
      "name": "Manage Sales",
      "tags": [
        "E-Tickets (Sales)",
        "Payments",
        "Sales",
        "SalesAggregates",
        "Shipments (Sales)"
      ]
    },
    {
      "name": "React To Changes",
      "tags": [
        "Webhooks"
      ]
    },
    {
      "name": "Manage Account",
      "tags": [
        "Addresses",
        "PaymentMethods",
        "User"
      ]
    }
  ]
}
